spring:
  application:
    name: tv-maze-api
  mongodb:
    uri: mongodb+srv://kairos_db:nM2rRIWuIipNdWKn@kairos-prueba.70ucjcq.mongodb.net/?appName=kairos-prueba
    database: tvmaze_db
tvmaze:
  api:
    base-url: "https://api.tvmaze.com"